### ISSUE TITLE
[Bug]: Game crashed when using Shattered Enchantment

### ISSUE THREAD

**Issue by Jouto55** [SiverDX/additional_enchantments#1]
Game crashed when I tried using the Shattered Enchantment.

---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 2024-01-25 12:37:41
Description: Ticking entity

java.lang.LinkageError: loader constraint violation: loader 'MC-BOOTSTRAP' @1283bb96 wants to load interface org.apache.logging.log4j.util.MessageSupplier. (org.apache.logging.log4j.util.MessageSupplier is in module org.apache.logging.log4j@2.19.0 of loader 'MC-BOOTSTRAP' @1283bb96, parent loader 'bootstrap')
	at net.minecraftforge.eventbus.EventBus.handleException(EventBus.java:329) ~[eventbus-6.0.5.jar%23137!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:320) ~[eventbus-6.0.5.jar%23137!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%23137!/:?] {}
	at net.minecraftforge.common.ForgeHooks.onLivingAttack(ForgeHooks.java:269) ~[forge-1.20.1-47.2.19-universal.jar%23191!/:?] {re:classloading}
	at net.minecraft.world.entity.LivingEntity.m_6469_(LivingEntity.java:1059) ~[client-1.20.1-20230612.114412-srg.jar%23186!/:?] {re:mixin,re:computing_frames,re:classloading,pl:mixin:APP:embeddiumplus.mixin.json:dynlights.lightsource.LivingEntityMixin,pl:mixin:APP:universalenchants.common.mixins.json:LivingEntityMixin,pl:mixin:APP:universalenchants.common.mixins.json:accessor.LivingEntityAccessor,pl:mixin:APP:do_a_barrel_roll.mixins.json:LivingEntityMixin,pl:mixin:APP:do_a_barrel_roll.mixins.json:roll.entity.LivingEntityMixin,pl:mixin:APP:do_a_barrel_roll.mixins.json:client.LivingEntityMixin,pl:mixin:A}
	at net.minecraft.world.entity.raid.Raider.m_6469_(Raider.java:295) ~[client-1.20.1-20230612.114412-srg.jar%23186!/:?] {re:classloading}
	at net.minecraft.world.entity.projectile.AbstractArrow.m_5790_(AbstractArrow.java:352) ~[client-1.20.1-20230612.114412-srg.jar%23186!/:?] {re:mixin,re:classloading,pl:mixin:APP:universalenchants.common.mixins.json:accessor.AbstractArrowAccessor,pl:mixin:APP:additional_enchantments.mixins.json:AbstractArrowAccess,pl:mixin:A}
	at de.cadentem.additional_enchantments.core.entity.ShardArrow.m_5790_(ShardArrow.java:38) ~[additional_enchantments-1.20.1-0.3.3-all.jar%23171!/:0.3.3] {re:classloading}
	at net.minecraft.world.entity.projectile.Projectile.m_6532_(Projectile.java:138) ~[client-1.20.1-20230612.114412-srg.jar%23186!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:additional_enchantments.mixins.json:ProjectileMixin,pl:mixin:A}
	at net.minecraft.world.entity.projectile.AbstractArrow.m_8119_(AbstractArrow.java:209) ~[client-1.20.1-20230612.114412-srg.jar%23186!/:?] {re:mixin,re:classloading,pl:mixin:APP:universalenchants.common.mixins.json:accessor.AbstractArrowAccessor,pl:mixin:APP:additional_enchantments.mixins.json:AbstractArrowAccess,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:693) ~[client-1.20.1-20230612.114412-srg.jar%23186!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.Level.m_46653_(Level.java:479) ~[client-1.20.1-20230612.114412-srg.jar%23186!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:embeddiumplus.mixin.json:dynlights.LevelMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:343) ~[client-1.20.1-20230612.114412-srg.jar%23186!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[client-1.20.1-20230612.114412-srg.jar%23186!/:?] {re:classloading}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:323) ~[client-1.20.1-20230612.114412-srg.jar%23186!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:893) ~[client-1.20.1-20230612.114412-srg.jar%23186!/:?] {re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[client-1.20.1-20230612.114412-srg.jar%23186!/:?] {re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:89) ~[client-1.20.1-20230612.114412-srg.jar%23186!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[client-1.20.1-20230612.114412-srg.jar%23186!/:?] {re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[client-1.20.1-20230612.114412-srg.jar%23186!/:?] {re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver}
	at java.lang.Thread.run(Thread.java:840) ~[?:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Suspected Mod: 
	Additional Enchantments (additional_enchantments), Version: 0.3.3
		at TRANSFORMER/additional_enchantments@0.3.3/de.cadentem.additional_enchantments.core.entity.ShardArrow.m_5790_(ShardArrow.java:38)
Stacktrace:
	at net.minecraftforge.eventbus.EventBus.handleException(EventBus.java:329) ~[eventbus-6.0.5.jar%23137!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:320) ~[eventbus-6.0.5.jar%23137!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%23137!/:?] {}
	at net.minecraftforge.common.ForgeHooks.onLivingAttack(ForgeHooks.java:269) ~[forge-1.20.1-47.2.19-universal.jar%23191!/:?] {re:classloading}
	at net.minecraft.world.entity.LivingEntity.m_6469_(LivingEntity.java:1059) ~[client-1.20.1-20230612.114412-srg.jar%23186!/:?] {re:mixin,re:computing_frames,re:classloading,pl:mixin:APP:embeddiumplus.mixin.json:dynlights.lightsource.LivingEntityMixin,pl:mixin:APP:universalenchants.common.mixins.json:LivingEntityMixin,pl:mixin:APP:universalenchants.common.mixins.json:accessor.LivingEntityAccessor,pl:mixin:APP:do_a_barrel_roll.mixins.json:LivingEntityMixin,pl:mixin:APP:do_a_barrel_roll.mixins.json:roll.entity.LivingEntityMixin,pl:mixin:APP:do_a_barrel_roll.mixins.json:client.LivingEntityMixin,pl:mixin:A}
	at net.minecraft.world.entity.raid.Raider.m_6469_(Raider.java:295) ~[client-1.20.1-20230612.114412-srg.jar%23186!/:?] {re:classloading}
	at net.minecraft.world.entity.projectile.AbstractArrow.m_5790_(AbstractArrow.java:352) ~[client-1.20.1-20230612.114412-srg.jar%23186!/:?] {re:mixin,re:classloading,pl:mixin:APP:universalenchants.common.mixins.json:accessor.AbstractArrowAccessor,pl:mixin:APP:additional_enchantments.mixins.json:AbstractArrowAccess,pl:mixin:A}
	at de.cadentem.additional_enchantments.core.entity.ShardArrow.m_5790_(ShardArrow.java:38) ~[additional_enchantments-1.20.1-0.3.3-all.jar%23171!/:0.3.3] {re:classloading}
	at net.minecraft.world.entity.projectile.Projectile.m_6532_(Projectile.java:138) ~[client-1.20.1-20230612.114412-srg.jar%23186!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:additional_enchantments.mixins.json:ProjectileMixin,pl:mixin:A}
	at net.minecraft.world.entity.projectile.AbstractArrow.m_8119_(AbstractArrow.java:209) ~[client-1.20.1-20230612.114412-srg.jar%23186!/:?] {re:mixin,re:classloading,pl:mixin:APP:universalenchants.common.mixins.json:accessor.AbstractArrowAccessor,pl:mixin:APP:additional_enchantments.mixins.json:AbstractArrowAccess,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:693) ~[client-1.20.1-20230612.114412-srg.jar%23186!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.Level.m_46653_(Level.java:479) ~[client-1.20.1-20230612.114412-srg.jar%23186!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:embeddiumplus.mixin.json:dynlights.LevelMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:343) ~[client-1.20.1-20230612.114412-srg.jar%23186!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[client-1.20.1-20230612.114412-srg.jar%23186!/:?] {re:classloading}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:323) ~[client-1.20.1-20230612.114412-srg.jar%23186!/:?] {re:classloading,pl:accesstransformer:B}
-- Entity being ticked --
Details:
	Entity Type: additional_enchantments:shard_arrow (de.cadentem.additional_enchantments.core.entity.ShardArrow)
	Entity ID: 24
	Entity Name: entity.additional_enchantments.shard_arrow
	Entity's Exact location: 33.08, 88.61, -27.53
	Entity's Block location: World: (33,88,-28), Section: (at 1,8,4 in 2,5,-2; chunk contains blocks 32,-64,-32 to 47,319,-17), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Entity's Momentum: -2.53, -0.88, -1.40
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.world.level.Level.m_46653_(Level.java:479) ~[client-1.20.1-20230612.114412-srg.jar%23186!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:embeddiumplus.mixin.json:dynlights.LevelMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:343) ~[client-1.20.1-20230612.114412-srg.jar%23186!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[client-1.20.1-20230612.114412-srg.jar%23186!/:?] {re:classloading}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:323) ~[client-1.20.1-20230612.114412-srg.jar%23186!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:893) ~[client-1.20.1-20230612.114412-srg.jar%23186!/:?] {re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[client-1.20.1-20230612.114412-srg.jar%23186!/:?] {re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:89) ~[client-1.20.1-20230612.114412-srg.jar%23186!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[client-1.20.1-20230612.114412-srg.jar%23186!/:?] {re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[client-1.20.1-20230612.114412-srg.jar%23186!/:?] {re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver}
	at java.lang.Thread.run(Thread.java:840) ~[?:?] {}

-- Affected level --
Details:
	All players: 0 total; []
	Chunk stats: 2209
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,70,0), Section: (at 0,6,0 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 17474 game time, 11415 day time
	Level name: a
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
	Level weather: Rain time: 117166 (now: false), thunder time: 147735 (now: false)
	Known server brands: forge
	Removed feature flags: 
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:893) ~[client-1.20.1-20230612.114412-srg.jar%23186!/:?] {re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[client-1.20.1-20230612.114412-srg.jar%23186!/:?] {re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:89) ~[client-1.20.1-20230612.114412-srg.jar%23186!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[client-1.20.1-20230612.114412-srg.jar%23186!/:?] {re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[client-1.20.1-20230612.114412-srg.jar%23186!/:?] {re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver}
	at java.lang.Thread.run(Thread.java:840) ~[?:?] {}

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.9, Azul Systems, Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Azul Systems, Inc.
	Memory: 582313272 bytes (555 MiB) / 1644167168 bytes (1568 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 5700X 8-Core Processor             
	Identifier: AuthenticAMD Family 25 Model 33 Stepping 2
	Microarchitecture: Zen 3
	Frequency (GHz): 3.40
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 3060 Ti
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x24c9
	Graphics card #0 versionInfo: DriverVersion=31.0.15.5123
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.60
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.60
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MB): 8192.00
	Memory slot #2 clockSpeed (GHz): 3.60
	Memory slot #2 type: DDR4
	Memory slot #3 capacity (MB): 8192.00
	Memory slot #3 clockSpeed (GHz): 3.60
	Memory slot #3 type: DDR4
	Virtual memory max (MB): 34702.80
	Virtual memory used (MB): 15235.97
	Swap memory total (MB): 2048.00
	Swap memory used (MB): 0.00
	JVM Flags: 9 total; -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=51 -XX:G1HeapRegionSize=32M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms1024m -Xmx8192m
	Loaded Shaderpack: (off)
	Server Running: true
	Player Count: 0 / 8; []
	Data Packs: vanilla, mod:mixinextras (incompatible), mod:universalenchants, mod:easyanvils, mod:geckolib, mod:do_a_barrel_roll (incompatible), mod:sculkhorde (incompatible), mod:easymagic, mod:puzzleslib, mod:puzzlesaccessapi, mod:forge, mod:textrues_embeddium_options (incompatible), mod:xaerominimap, mod:oculus, mod:enchantinginfuser, mod:embeddium, mod:embeddiumplus (incompatible), mod:xaeroworldmap, mod:additional_enchantments (incompatible)
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge'
	Launched Version: 1.20.1
	ModLauncher: 10.0.9+10.0.9+main.dcd20f30
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.5.jar eventbus PLUGINSERVICE 
		fmlloader-1.20.1-47.2.19.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.20.1-47.2.19.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.20.1-47.2.19.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.20.1-47.2.19.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.20.1-47.2.19.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.9.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.9.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		client-1.20.1-20230612.114412-srg.jar             |Minecraft                     |minecraft                     |1.20.1              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		mixinextras-forge-0.3.5.jar                       |MixinExtras                   |mixinextras                   |0.3.5               |DONE      |Manifest: NOSIGNATURE
		UniversalEnchants-v8.0.0-1.20.1-Forge.jar         |Universal Enchants            |universalenchants             |8.0.0               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		EasyAnvils-v8.0.1-1.20.1-Forge.jar                |Easy Anvils                   |easyanvils                    |8.0.1               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		geckolib-forge-1.20.1-4.4.jar                     |GeckoLib 4                    |geckolib                      |4.4                 |DONE      |Manifest: NOSIGNATURE
		do_a_barrel_roll-forge-3.5.0+1.20.1.jar           |Do a Barrel Roll              |do_a_barrel_roll              |3.5.0+1.20.1        |DONE      |Manifest: NOSIGNATURE
		sculkhorde-1.20.1-0.8.4.jar                       |Sculk Horde                   |sculkhorde                    |1.20.1-0.8.4        |DONE      |Manifest: NOSIGNATURE
		EasyMagic-v8.0.1-1.20.1-Forge.jar                 |Easy Magic                    |easymagic                     |8.0.1               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		PuzzlesLib-v8.1.14-1.20.1-Forge.jar               |Puzzles Lib                   |puzzleslib                    |8.1.14              |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		puzzlesaccessapi-forge-8.0.7.jar                  |Puzzles Access Api            |puzzlesaccessapi              |8.0.7               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		forge-1.20.1-47.2.19-universal.jar                |Forge                         |forge                         |47.2.19             |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		textrues_embeddium_options-0.1.3+mc1.20.1.jar     |TexTrue's Embeddium Options   |textrues_embeddium_options    |0.1.3+mc1.20.1      |DONE      |Manifest: NOSIGNATURE
		Xaeros_Minimap_23.9.3_Forge_1.20.jar              |Xaero's Minimap               |xaerominimap                  |23.9.3              |DONE      |Manifest: NOSIGNATURE
		oculus-mc1.20.1-1.6.13.jar                        |Oculus                        |oculus                        |1.6.13              |DONE      |Manifest: NOSIGNATURE
		EnchantingInfuser-v8.0.2-1.20.1-Forge.jar         |Enchanting Infuser            |enchantinginfuser             |8.0.2               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		embeddium-0.2.18+mc1.20.1.jar                     |Embeddium                     |embeddium                     |0.2.18+mc1.20.1     |DONE      |Manifest: NOSIGNATURE
		embeddiumplus-1.20.1-v1.2.3-build.jar             |Embeddium++                   |embeddiumplus                 |1.2.3               |DONE      |Manifest: NOSIGNATURE
		XaerosWorldMap_1.37.2_Forge_1.20.jar              |Xaero's World Map             |xaeroworldmap                 |1.37.2              |DONE      |Manifest: NOSIGNATURE
		additional_enchantments-1.20.1-0.3.3-all.jar      |Additional Enchantments       |additional_enchantments       |0.3.3               |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 7e20ef97-d4c6-4043-98c2-ca4dcd0651ee
	FML: 47.2
	Forge: net.minecraftforge:47.2.19
#@!@# Game crashed! Crash report saved to: #@!@# C:\Users\Joshua\AppData\Roaming\PrismLauncher\instances\Bugfixger\.minecraft\crash-reports\crash-2024-01-25_12.37.41-server.txt
[12:37:42] [Server thread/INFO] [minecraft/MinecraftServer]: Saving chunks for level 'ServerLevel[a]'/minecraft:overworld
[12:37:42] [Server thread/INFO] [co.gi.sc.co.SculkHorde/]: Saving events
[12:37:43] [Server thread/INFO] [minecraft/MinecraftServer]: Saving chunks for level 'ServerLevel[a]'/minecraft:the_nether
[12:37:43] [Server thread/INFO] [minecraft/MinecraftServer]: Saving chunks for level 'ServerLevel[a]'/minecraft:the_end
[12:37:43] [Server thread/INFO] [minecraft/MinecraftServer]: ThreadedAnvilChunkStorage (a): All chunks are saved
[12:37:43] [Server thread/INFO] [minecraft/MinecraftServer]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[12:37:43] [Server thread/INFO] [minecraft/MinecraftServer]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[12:37:43] [Server thread/INFO] [minecraft/MinecraftServer]: ThreadedAnvilChunkStorage: All dimensions are saved
Process exited with code -1.

**Comment by SiverDX** [comment]
Fixed in https://www.curseforge.com/minecraft/mc-mods/additional-enchantments/files/5059298

**Comment by Jouto55** [comment]
Tested the mod with fix, no longer crashes. 👍
